version: '3.3'
services:
  # frourio:
  #   container_name: frourio-${PROJECT_NAME}
  #   tty: true
  #   build: 
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - db
  #   ports:
  #     - "8000:8000"
  #     - "30743:30743"
  #   volumes:
  #     - ./app:/app
  db:
    image: mysql:5.7
    container_name: mysql-${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  pma:
    container_name: pma-${PROJECT_NAME}
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
    - "8080:80"
    environment:
      - UPLOAD_LIMIT=20480K
    links:
      - db
  redis:
    container_name: redis-${PROJECT_NAME}
    image: "redis:latest"
    ports:
      - "6379:6379"
    volumes:
      - "./data/redis:/data"
