version: '3.3'
services:
  frourio:
    container_name: frourio-${PROJECT_NAME}
    tty: true
    build: 
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - ./app:/app