version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: mysql-${PROJECT_NAME}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${PROJECT_NAME}
      MYSQL_USER: ${PROJECT_NAME}
      MYSQL_PASSWORD: ${PROJECT_NAME}
      TZ: 'Asia/Tokyo'
      command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  pma:
    container_name: pma-${PROJECT_NAME}
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      UPLOAD_LIMIT: 20480K
    ports:
    - "8080:80"
    links:
      - db

