version: '3.3'
services:
  backend:
    container_name: backend-${PROJECT_NAME}
    build:
      context: ./app/server
      dockerfile: Dockerfile
    environment:
      HOST: http://localhost:3000
      NODE_ENV: production
      PORT: 3000
    ports:
      - "3000:3000"
