import { Table,
  Thead,
  Tbody,
  Tfoot,
  Tr,
  Th,
  Td,
 } from "@chakra-ui/react"

const PageHeader = () => {
  return (
    <>
    <Table variant="striped" colorScheme="gray" >
      <Thead>
        <Tr>
          <Th>入出庫日</Th>
          <Th>理由</Th>
          <Th>備考</Th>
          <Th>入庫数</Th>
          <Th>出庫数</Th>
          <Th>単位</Th>
          <Th>登録者</Th>
          <Th>予約日</Th>
          <Th>予約者</Th>
        </Tr>
      </Thead>
      <Tbody>
        <Tr>
          <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td></Td>
          <Td>50</Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
        <Tr>
        <Td>21/4/1</Td>
          <Td>バラ出荷</Td>
          <Td>見積番号ｘｘｘｘ</Td>
          <Td>1000</Td>
          <Td></Td>
          <Td>ケース</Td>
          <Td>田中</Td>
          <Td>21/2/31</Td>
          <Td>平川</Td>
        </Tr>
      </Tbody>
      <Tfoot>
        <Tr>
          <Th>To convert</Th>
          <Th>into</Th>
          <Th>multiply by</Th>
        </Tr>
      </Tfoot>
    </Table>
    </>
  )
}

export default PageHeader