FROM node:16.13-alpine

RUN apk add --no-cache openssl

WORKDIR /server

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .

RUN touch .env.production

RUN yarn build

COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENV NODE_ENV=production

EXPOSE 3000

ENTRYPOINT ["docker-entrypoint.sh"]
CMD ["node", "index.js"]
