-- AlterTable
ALTER TABLE `Item` ADD COLUMN `costUnitName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `gradeName` VARCHAR(191) NULL,
    ADD COLUMN `unitName` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `warehouseName` VARCHAR(191) NOT NULL DEFAULT '';
